name: testing-ci-cd

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install dependency
        run: yarn install

      - name: deploy with gh-page
        run: yarn deploy

      - name: test with jest
        run: yarn test

      # Runs a set of commands using the runners shell

      - name: notification for completed deployment
        run: echo it's completed
