name: testing-ci-cd

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install dependency
        run: yarn install

      - name: start port 3000 and test it
        run: yarn ci

      - name: deploy to github-pages
        run: |
        git config --global user.email "jinho6225@hotmail.com"
        git config --global user.name "jinho6225"
        yarn deploy
